# Generated by Django 2.0.5 on 2018-07-20 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_auto_20180718_0244'),
        ('property', '0008_auto_20180624_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicants', models.ManyToManyField(to='accounts.Customer')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Employee')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='property.Property')),
            ],
        ),
    ]
