# Generated by Django 2.0.5 on 2018-07-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
