# Generated by Django 2.0.5 on 2018-07-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0002_lease_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='lease',
            name='monthly_fees',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='lease',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=9),
        ),
    ]
