# Generated by Django 2.0.5 on 2018-07-29 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0005_lease_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
