# Generated by Django 2.0.5 on 2018-07-29 23:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0006_auto_20180729_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
