# Generated by Django 2.0.5 on 2018-06-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.IntegerField(choices=[(1, 'Maintenance'), (2, 'Leasing'), (3, 'Management'), (4, 'Front Desk')], default=4),
        ),
    ]
