# Generated by Django 2.0.5 on 2018-06-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_publicly_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
        migrations.AddField(
            model_name='property',
            name='street_address',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
