# Generated by Django 2.0.5 on 2018-06-24 16:50

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20180624_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='state',
            field=localflavor.us.models.USStateField(default='', max_length=2),
        ),
    ]
