# Generated by Django 2.0.5 on 2018-06-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20180624_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='unit',
            field=models.CharField(default='', max_length=10),
        ),
    ]
