# Generated by Django 2.0.5 on 2018-06-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20180624_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='num_bathrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='num_bedrooms',
            field=models.IntegerField(default=1),
        ),
    ]
