# Generated by Django 2.0.5 on 2018-07-20 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20180624_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='occupied_by',
        ),
    ]
