# Generated by Django 2.0.5 on 2018-07-18 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20180624_1747'),
        ('housing_application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housingapplication',
            name='lease_duration',
        ),
        migrations.AddField(
            model_name='housingapplication',
            name='property',
            field=models.ForeignKey(default='380a0e1e-95ae-4863-8b75-d2cef6d41b18', on_delete=django.db.models.deletion.PROTECT, to='property.Property'),
        ),
        migrations.AlterField(
            model_name='housingapplication',
            name='application_status',
            field=models.CharField(choices=[('APPLIED', 'Submitted'), ('IN_REVIEW', 'In review'), ('DENIED', 'Denied'), ('APPROVED', 'Approved')], default='APPLIED', max_length=15),
        ),
    ]
