# Generated by Django 2.0.5 on 2018-07-20 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing_application', '0002_auto_20180718_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housingapplication',
            name='applicants',
        ),
    ]
