# Generated by Django 2.0.5 on 2018-07-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0002_lease_is_approved'),
        ('housing_application', '0003_remove_housingapplication_applicants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housingapplication',
            name='lease_start',
        ),
        migrations.AddField(
            model_name='housingapplication',
            name='lease',
            field=models.ManyToManyField(to='lease.Lease'),
        ),
    ]
