# Generated by Django 2.0.5 on 2018-07-22 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing_application', '0004_auto_20180722_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housingapplication',
            options={'permissions': (('can_set_housing_application_status', 'Change housing application status'),)},
        ),
    ]
